### ISSUE TITLE
Minor suggestion

### ISSUE THREAD

**Issue by grantmcdermott** [jthomasmock/pdftools-guide#1]
Really nice walkthrough. I hesitate to raise this as an issue &mdash; especially since there are always multiple ways to complete any particular task in R &mdash; but you can save quite a few lines by using `readr::read_fwf()` to coerce the raw text directly to a data frame.

```r
## +/- line 141 of the Rmd file
table_start <- stringr::str_which(raw_text, "Production") ## Changed since we're dropping the first row anyway
table_end <- stringr::str_which(raw_text, "Total Used")
## Trim the table to the start/end (NB: Don't drop whitespace this time!)
table_trimmed <- raw_text[table_start:table_end]

beer_df <- 
  read_fwf(table_trimmed, fwf_empty(table_trimmed)) %>% 
  magrittr::set_colnames(c("type", "month_current", "month_prior_year", "ytd_current", "ytd_prior_year")
```

Again, I'm not suggesting this is inherently better, but I've found the `read_fwf(., fwf_empty(.))` shortcut very useful for extracting tabular data from PDFs, as well as old school web pages that can only be read in as text initially.

**Comment by jthomasmock** [comment]
Will add! I had done some attempts via `read.table` that failed, and so the demo was aimed at examples where this method in theory wouldn't work (varying white space between columns), but this is definitely worth adding. Thanks!

I believe that either `readr::read_fwf()` w/ `fwf_empty()`, `readr::read_table()` or `readr::read_table2()` all work for this example PDF, I'll keep the note referring to this issue and the original workflow in case there are in fact edge-cases where the `readr` methods fail.
